artifacts_root: ./artifacts


data_ingestion:
  root_dir: ./artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing
  local_data_file: ./artifacts/data_ingestion/data.zip
  unzip_dir: ./artifacts/data_ingestion


prepare_base_model:
  root_dir: ./artifacts/prepare_base_model
  base_model_path: ./artifacts/prepare_base_model/base_model.pth
  updated_base_model_path: ./artifacts/prepare_base_model/base_model_updated.pth


logs:
  root_dir: ./artifacts/logs
  tensorboard: ./artifacts/logs/tensorboard
  lightning: ./artifacts/logs/lightning
  mlflow: ./artifacts/logs/mlruns



training:
  root_dir: ./artifacts/training
  trained_model_path: ./artifacts/training/model.pth